# Generated by Django 6.0.4 on 2026-04-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_storage_options_storage_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
